### ISSUE TITLE
Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function

### ISSUE THREAD

**Issue by ashikpy** [blenderskool/react-code-block#3]
i had the basic boiler plate example given in the official documentation, and it's not working, and throwing this error
<img width="967" alt="image" src="https://github.com/user-attachments/assets/3ce07820-e2b6-4183-b4e4-59dc1cc27655">

Framework - Nextjs 14.2.5
Used Bun ( yeah i also tried with npm too )

**Comment by blenderskool** [comment]
@ashikpy Can you confirm if you are using React Server Components? react-code-block can only be used as a Client Component right now.
https://react-code-block.netlify.app/usage/with-react-server-components

**Comment by ashikpy** [comment]
I'm so embarrassed, to say that i forgot to `use client`, sorry for that!

**Comment by blenderskool** [comment]
No problem!
