### ISSUE TITLE
How can I add support for a new language?

### ISSUE THREAD

**Issue by FerretAngel** [blenderskool/react-code-block#4]
I took a look at [prism-react-renderer](https://github.com/FormidableLabs/prism-react-renderer#custom-language-support)
But I didn't understand, so I asked the AI.
![image](https://github.com/user-attachments/assets/e154b280-9d0b-404a-9cfc-c4631ae05426)
The new version doesn't have this file.

**Comment by blenderskool** [comment]
`prism-react-renderer` (which is the library used by React Code Block under the hood) has some docs around adding custom language support – https://github.com/FormidableLabs/prism-react-renderer?tab=readme-ov-file#custom-language-support
